name: conf2mark

on:
#  push:
#    branches: [main] # Define on which branch this workflow triggers
  workflow_dispatch: # Enables manual trigger

jobs:  
  conf2mark:
    runs-on: self-hosted
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
     
      - name: Build docs
        run: |
          mkdir export;
          unzip test/Confluence-space-export-135450-6.html.zip -d export;
          docker run -i -v $PWD:$PWD aerostitch/confluence-to-markdown npm run start $PWD/export $PWD/docs
  
